<?php require("about.php"); ?>
<?php require("blog.php"); ?>
<?php require("contact.php"); ?>
<?php require("index.php"); ?>
<?php require("index-2.php"); ?>
<?php require("index-3.php"); ?>
<?php require("index-4.php"); ?>
<?php require("index-single.php"); ?>
<?php require("index-single-2.php"); ?>
<?php require("index-single-3.php"); ?>
<?php require("index-single-4.php"); ?>
<?php require("landing.php"); ?>
<?php require("portfolio.php"); ?>
<?php require("services.php"); ?>
<?php require("single-post.php"); ?>
<?php require("single-project.php"); ?>